# Generated by Django 6.0.1 on 2026-06-03 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('buildingID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='building_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='LogData',
            fields=[
                ('logdataID', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('user_identifier', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personID', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('martialstatus', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('nationalid', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReserveStatus',
            fields=[
                ('reservestatusID', models.IntegerField(choices=[(1, 'active'), (2, 'inactive')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('roomstatusID', models.IntegerField(choices=[(1, 'reservable'), (2, 'reserved'), (3, 'maintenance')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('apartmentID', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('kitchen', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('livingroom', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='app.building')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to='app.person')),
                ('roomstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.roomstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservatioID', models.AutoField(primary_key=True, serialize=False)),
                ('startdate', models.DateField()),
                ('finaldate', models.DateField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.apartment')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.building')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
                ('reservestatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.reservestatus')),
            ],
        ),
    ]
